import type { CSSProperties } from "react";

export const mono = '"JetBrains Mono", monospace';
export const blue = "#0066ff";

export const styles: Record<string, CSSProperties> = {
  site: {
    fontFamily: '"Inter", sans-serif',
    background: "#060608",
    color: "#fff",
    minHeight: "100vh",
    position: "relative",
    overflowX: "hidden",
  },
  nav: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 40px",
    borderBottom: "1px solid rgba(0,102,255,0.12)",
    background: "rgba(6,6,8,0.75)",
    backdropFilter: "blur(12px)",
  },
  navLogo: {
    fontFamily: mono,
    fontSize: 15,
    fontWeight: 700,
    color: blue,
    letterSpacing: "0.05em",
  },
  navLinks: { display: "flex", gap: 28, alignItems: "center" },
  navLink: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
    textDecoration: "none",
    fontFamily: mono,
    transition: "color 0.15s",
  },
  navCta: {
    fontFamily: mono,
    fontSize: 12,
    fontWeight: 700,
    color: "#000",
    background: blue,
    padding: "8px 18px",
    borderRadius: 4,
    textDecoration: "none",
    letterSpacing: "0.04em",
    transition: "background 0.15s",
  },
  hero: {
    position: "relative",
    zIndex: 2,
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: "120px 24px 80px",
  },
  terminalWindow: {
    background: "rgba(10,12,10,0.85)",
    border: "1px solid rgba(0,102,255,0.25)",
    borderRadius: 8,
    marginBottom: 36,
    width: "100%",
    maxWidth: 520,
    backdropFilter: "blur(8px)",
    textAlign: "left",
    overflow: "hidden",
  },
  terminalBar: {
    background: "rgba(0,102,255,0.06)",
    borderBottom: "1px solid rgba(0,102,255,0.15)",
    padding: "8px 14px",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  tb: { width: 10, height: 10, borderRadius: "50%" },
  terminalPath: {
    fontFamily: mono,
    fontSize: 11,
    color: "rgba(0,102,255,0.5)",
    marginLeft: 8,
  },
  terminalBody: {
    padding: "16px 18px",
    fontFamily: mono,
    fontSize: 12,
    lineHeight: 1.8,
    minHeight: 110,
  },
  tLine: { color: "rgba(255,255,255,0.4)" },
  prompt: { color: blue },
  cmd: { color: "#fff" },
  out: { color: "rgba(255,255,255,0.38)" },
  cursor: {
    display: "inline-block",
    width: 8,
    height: 13,
    background: blue,
    verticalAlign: "middle",
    animation: "blink 1s step-end infinite",
  },
  heroEyebrow: {
    fontFamily: mono,
    fontSize: 11,
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: blue,
    marginBottom: 16,
  },
  heroSub: {
    fontSize: 15,
    color: "rgba(255,255,255,0.45)",
    maxWidth: 400,
    lineHeight: 1.7,
    marginBottom: 32,
  },
  countdown: {
    display: "flex",
    gap: 12,
    marginBottom: 32,
    justifyContent: "center",
    flexWrap: "wrap",
  },
  cdUnit: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "rgba(0,102,255,0.04)",
    border: "1px solid rgba(0,102,255,0.2)",
    borderRadius: 6,
    padding: "14px 20px 10px",
    minWidth: 76,
  },
  cdNum: {
    fontFamily: mono,
    fontSize: 28,
    fontWeight: 700,
    color: blue,
    lineHeight: 1,
    fontVariantNumeric: "tabular-nums",
  },
  cdLbl: {
    fontFamily: mono,
    fontSize: 9,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color: "rgba(0,102,255,0.4)",
    marginTop: 6,
  },
  infoRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 32,
  },
  chip: {
    fontFamily: mono,
    fontSize: 14,
    color: "rgba(255,255,255,0.5)",
    border: "1px solid rgba(0,102,255,0.15)",
    borderRadius: 4,
    padding: "5px 12px",
  },
  btnReg: {
    fontFamily: mono,
    fontSize: 13,
    fontWeight: 700,
    color: "#000",
    background: blue,
    padding: "14px 32px",
    borderRadius: 4,
    textDecoration: "none",
    letterSpacing: "0.04em",
    transition: "background 0.15s, transform 0.1s",
    display: "inline-block",
  },
  divider: {
    border: "none",
    borderTop: "1px solid rgba(0,102,255,0.1)",
    margin: "0 40px",
  },
  section: {
    position: "relative",
    zIndex: 2,
    padding: "80px 40px",
    maxWidth: 960,
    margin: "0 auto",
  },
  secHeader: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 32,
  },
  secBar: {
    width: 3,
    height: 28,
    background: blue,
    borderRadius: 2,
  },
  h2: { fontSize: 28, fontWeight: 700 },
  aboutText: {
    fontSize: 15,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.8,
    maxWidth: 680,
    marginLeft: "auto",
    marginRight: "auto",
  },
  teamGrid: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 16,
    maxWidth: 680,
    margin: "0 auto",
  },
  teamCard: {
    flex: "1 1 220px",
    maxWidth: 320,
    background: "rgba(0,102,255,0.08)",
    border: "1px solid rgba(0,102,255,0.25)",
    borderRadius: 8,
    padding: 20,
  },
  teamIcon: { fontSize: 18, marginBottom: 8 },
  teamName: {
    fontFamily: mono,
    fontSize: 14,
    fontWeight: 700,
    color: blue,
    marginBottom: 4,
  },
  teamDesc: {
    fontSize: 12,
    color: "rgba(255,255,255,0.45)",
    lineHeight: 1.6,
  },
  teamLink: {
    fontSize: 12,
    color: blue,
    textDecoration: "none",
    lineHeight: 1.6,
    display: "block",
    marginTop: 4,
  },
  teamPhone: {
    fontSize: 12,
    color: "rgba(255,255,255,0.45)",
    lineHeight: 1.6,
  },
  programGrid: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 16,
    marginBottom: 24,
  },
  programCard: {
    flex: "1 1 220px",
    maxWidth: 320,
    background: "rgba(0,102,255,0.08)",
    border: "1px solid rgba(0,102,255,0.25)",
    borderRadius: 8,
    padding: 20,
  },
  programDay: {
    fontFamily: mono,
    fontSize: 12,
    fontWeight: 700,
    color: "rgba(255,255,255,0.3)",
    textTransform: "uppercase" as const,
    letterSpacing: 1,
    marginBottom: 4,
  },
  programTitle: {
    fontFamily: mono,
    fontSize: 15,
    fontWeight: 700,
    color: blue,
    marginBottom: 12,
  },
  programSessions: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  programSession: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  programSessionName: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.4,
  },
  programDuration: {
    fontFamily: mono,
    fontSize: 11,
    color: "rgba(255,255,255,0.25)",
    whiteSpace: "nowrap" as const,
  },
  programNote: {
    fontSize: 13,
    color: "rgba(255,255,255,0.35)",
    lineHeight: 1.7,
    maxWidth: 680,
    margin: "0 auto",
    textAlign: "center" as const,
  },
  prizesBox: {
    background: "rgba(0,102,255,0.08)",
    border: "1px solid rgba(0,102,255,0.25)",
    borderRadius: 8,
    padding: 32,
    maxWidth: 480,
    margin: "0 auto",
  },
  prizesAmount: {
    fontFamily: mono,
    fontSize: 28,
    fontWeight: 700,
    color: blue,
    marginBottom: 12,
  },
  prizesDesc: {
    fontSize: 14,
    color: "rgba(255,255,255,0.45)",
    lineHeight: 1.7,
  },
  prizesIntro: {
    fontSize: 14,
    color: "rgba(255,255,255,0.5)",
    textAlign: "center" as const,
    marginBottom: 20,
    maxWidth: 500,
    marginLeft: "auto",
    marginRight: "auto",
  },
  prizesList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    maxWidth: 560,
    margin: "0 auto",
  },
  prizesItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "rgba(0,102,255,0.08)",
    border: "1px solid rgba(0,102,255,0.2)",
    borderRadius: 8,
    padding: "14px 20px",
    gap: 12,
  },
  prizesItemAward: {
    fontFamily: mono,
    fontSize: 13,
    fontWeight: 700,
    color: blue,
  },
  prizesItemRecipients: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
    textAlign: "right" as const,
  },
  footerCta: {
    position: "relative",
    zIndex: 2,
    textAlign: "center",
    padding: "60px 24px",
    borderTop: "1px solid rgba(0,102,255,0.1)",
  },
  footerCtaText: {
    fontFamily: mono,
    fontSize: 13,
    color: "rgba(0,102,255,0.5)",
    marginBottom: 20,
  },
  footer: {
    position: "relative",
    zIndex: 2,
    borderTop: "1px solid rgba(0,102,255,0.1)",
    padding: "48px 40px 32px",
  },
  footerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 32,
    maxWidth: 900,
    margin: "0 auto 32px",
  },
  footerTitle: {
    fontFamily: mono,
    fontSize: 14,
    fontWeight: 700,
    color: blue,
    marginBottom: 12,
  },
  footerBody: {
    fontSize: 13,
    color: "rgba(255,255,255,0.4)",
    lineHeight: 1.7,
  },
  footerLinks: {
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  footerLink: {
    fontFamily: mono,
    fontSize: 12,
    color: "rgba(255,255,255,0.4)",
    textDecoration: "none",
    transition: "color 0.15s",
  },
  footerBottom: {
    textAlign: "center",
    fontFamily: mono,
    fontSize: 11,
    color: "rgba(255,255,255,0.2)",
    borderTop: "1px solid rgba(0,102,255,0.08)",
    paddingTop: 20,
    maxWidth: 900,
    margin: "0 auto",
  },
};
